### ISSUE TITLE
Pext does not start on Manjaro Linux

### ISSUE THREAD

**Issue by tastyminerals** [Pext/Pext#148]
**Describe the bug**
pext throws Qt errors

**To Reproduce**
1. `pip3 install pext --user`
2. $ pext
3. See error

**Expected behavior**
pext should start and run normally

**Screenshots**
```
[user@user-pc ~]$ pext
qt5ct: using qt5ct plugin
Using locale: en_US (system locale)
Localization loaded: True
QQmlApplicationEngine failed to load component
file:///home/user/.local/lib/python3.7/site-packages/pext/qml/main.qml:25 module "QtQuick.Extras" is not installed
file:///home/user/.local/lib/python3.7/site-packages/pext/qml/main.qml:22 module "QtQuick.Controls.Styles" is not installed
file:///home/user/.local/lib/python3.7/site-packages/pext/qml/main.qml:21 module "QtQuick.Controls" is not installed
file:///home/user/.local/lib/python3.7/site-packages/pext/qml/main.qml:25 module "QtQuick.Extras" is not installed
file:///home/user/.local/lib/python3.7/site-packages/pext/qml/main.qml:22 module "QtQuick.Controls.Styles" is not installed
file:///home/user/.local/lib/python3.7/site-packages/pext/qml/main.qml:21 module "QtQuick.Controls" is not installed
file:///home/user/.local/lib/python3.7/site-packages/pext/qml/main.qml:25 module "QtQuick.Extras" is not installed
file:///home/user/.local/lib/python3.7/site-packages/pext/qml/main.qml:22 module "QtQuick.Controls.Styles" is not installed
file:///home/user/.local/lib/python3.7/site-packages/pext/qml/main.qml:21 module "QtQuick.Controls" is not installed

Traceback (most recent call last):
  File "/home/user/.local/bin/pext", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/pext/__main__.py", line 3512, in main
    window = Window(locale_manager)
  File "/home/user/.local/lib/python3.7/site-packages/pext/__main__.py", line 1985, in __init__
    self.window = self.engine.rootObjects()[0]
IndexError: list index out of range
```

**Desktop (please complete the following information):**
 - OS: Manjaro 
 - Pext Version 0.21

**Comment by tastyminerals** [comment]
Quick fix is:
```
sudo pacman -S qt5-tools
sudo pacman -S qt5-quickcontrols
sudo pacman -S qt5-graphicaleffects
```

**Comment by TheLastProject** [comment]
Your quick fix makes some sense, but I would prefer if it could work without those packages.

From a quick web search: could you try uninstalling them again and launching Pext as follows?
`QML2_IMPORT_PATH=$HOME/.local/lib/python3.7/site-packages/PyQt5/Qt/qml pext`?

**Comment by tastyminerals** [comment]
I am getting the same error with `QML2_IMPORT_PATH` var.

**Comment by vanyasem** [comment]
Why wouldn't you go for an AUR package on Manjaro?

**Comment by TheLastProject** [comment]
Even then, the pip version should just work. This issue could affect other distros too.
