### ISSUE TITLE
execution on Linux fails

### ISSUE THREAD

**Issue by tissatussa** [Pext/Pext#406]
**Describe the bug**
i installed pext by pip3 and it succeeded, including its path in my $PATH.

**To Reproduce**
```
tissatussa@tissatussa-HP-Elite-x2-1012-G2:~/.local/bin$ python3 -m pext
Using locale: en_US (system locale)
Localization loaded: False
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tissatussa/.local/lib/python3.8/site-packages/pext/__main__.py", line 3313, in <module>
    main(UIType.Qt5)
  File "/home/tissatussa/.local/lib/python3.8/site-packages/pext/__main__.py", line 3262, in main
    from ui.qt5 import Window, Tray, HotkeyHandler, SignalHandler
ModuleNotFoundError: No module named 'ui'

tissatussa@tissatussa-HP-Elite-x2-1012-G2:~/.local/bin$ python3 pext
Traceback (most recent call last):
  File "pext", line 8, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'ui_type'

```

**Expected behavior**
pext should just start

**Desktop (please complete the following information):**
 - OS: 20.04
 - i successfully (?) installed Pext 0.32 but --version gives the same 'ui_type' error 
 - Module version: --

**Additional context**
i think some qt5 module is missing ..

**Comment by TheLastProject** [comment]
Hmm... this sounds like it is related to https://github.com/Pext/Pext/issues/382.

Can you try the development version?

```
pip3 install git+https://github.com/Pext/Pext
```

**Comment by tissatussa** [comment]
> Hmm... this sounds like it is related to #382.

i saw that recent Issue .. indeed, after installing i have an icon in my XFCE start menu, like any other application .. but clicking it gives nothing .. and Taskmanager shows pext is not loaded in memory (first i thought i should use some hotkey to open pext) .. so, i executed pext in terminal and you saw the output.

btw. while installing, i had these warnings : 
 
```
Installing collected packages: psutil, PyOpenGL, requests, pycparser, cffi, bcrypt, paramiko, PyQt5-sip, pyqt5, dulwich, evdev, python-xlib, pynput, pathtools, watchdog, pext
  WARNING: The scripts pylupdate5, pyrcc5 and pyuic5 are installed in '/home/tissatussa/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script dulwich is installed in '/home/tissatussa/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script watchmedo is installed in '/home/tissatussa/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pext_dev is installed in '/home/tissatussa/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed PyOpenGL-3.1.5 PyQt5-sip-12.9.0 bcrypt-3.2.0 cffi-1.14.6 dulwich-0.20.8 evdev-1.4.0 paramiko-2.7.2 pathtools-0.1.2 pext-0.32 psutil-5.7.3 pycparser-2.20 pynput-1.7.1 pyqt5-5.15.1 python-xlib-0.31 requests-2.24.0 watchdog-0.10.3

tissatussa@tissatussa-HP-Elite-x2-1012-G2:~/Compiled$ whereis pext
pext:
tissatussa@tissatussa-HP-Elite-x2-1012-G2:~/Compiled$ echo $PATH
/usr/include/mkl:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

so i had to restart my Linux (which should not be needed) because i found these few code lines at the bottom of ~/.local/bin/.profile :

```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```

this is also stated in your readme .. indeed, after restart that (pext) folder was added to my PATH, although my above terminal output shows that i executed pext in its folder (so no PATH is needed) .. i should look into the .desktop launcher file :-)

**Comment by tissatussa** [comment]
i did not try the development version yet

**Comment by tissatussa** [comment]
i think i located the launcher : `~/.local/share/applications/io.pext.pext.desktop` :

```
[Desktop Entry]
Type=Application
Name=Pext
Comment=Python-based extendable tool
Categories=Utility;
Exec=pext
Icon=pext
StartupNotify=false
Terminal=false
```

because pext is in my PATH, this should work !?

**Comment by TheLastProject** [comment]
That should work, yeah. But it may have been broken on stable. I haven't been able to put a new stable release out for quite long as the Linux build is broken.

**Comment by TheLastProject** [comment]
This should be fixed in 0.34.
