### ISSUE TITLE
macOS .dmg has issues running pip install

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#86]
```
Counting objects: 68, done.
Compressing objects: 100% (7/7), done.
Total 68 (delta 1), reused 1 (delta 0), pack-reused 61
Checking out d1e7e0889aa35a0b751bf6dc4ee598921e3fdeaa
Traceback (most recent call last):
  File "runpy.pyc", line 183, in _run_module_as_main
  File "runpy.pyc", line 142, in _get_module_details
  File "runpy.pyc", line 109, in _get_module_details
  File "pip/__init__.pyc", line 43, in <module>
  File "pip/utils/__init__.pyc", line 23, in <module>
  File "pip/locations.pyc", line 10, in <module>
  File "distutils/command/install.pyc", line 18, in <module>
ImportError: cannot import name 'USER_BASE'
```

**Comment by TheLastProject** [comment]
Fixed in 635637a90baa436a8c40cd3a58620dbc9aa9bbaf

**Comment by TheLastProject** [comment]
Unfortunately, this is apparently still broken after all.

The following error remains:
```
Collecting emoji
  Using cached emoji-0.4.5.tar.gz
    Complete output from command python setup.py egg_info:
    /Applications/Pext.app/Contents/Resources/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'extras_require'
      warnings.warn(msg)
    /Applications/Pext.app/Contents/Resources/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'
      warnings.warn(msg)
    /Applications/Pext.app/Contents/Resources/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: invalid command 'egg_info'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-0mu3lzbk/emoji/
```

**Comment by TheLastProject** [comment]
This seems to be fixed now.
